/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.muratti66.RadioRemoteController;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.muratti66.RadioRemoteController.enc.ConfigClass;
import java.lang.reflect.Type;
import java.awt.List;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author muratti66
 */
public class RadioMemoryJFrame extends javax.swing.JFrame {
    private RadioJFrame radioFrame = null;
    /**
     * Creates new form RadioMemoryJFrame
     */
    public RadioMemoryJFrame(RadioJFrame radioFrame) {
        this.setVisible(true);
        this.radioFrame = radioFrame;
        initComponents();
        loadAllFrequance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        channel1jButton2 = new javax.swing.JButton();
        channel2jButton2 = new javax.swing.JButton();
        channel3jButton4 = new javax.swing.JButton();
        channel3jButton5 = new javax.swing.JButton();
        channel1jButton3 = new javax.swing.JButton();
        channel2jButton3 = new javax.swing.JButton();
        channel3jButton6 = new javax.swing.JButton();
        channel3jButton7 = new javax.swing.JButton();
        channel1jButton = new javax.swing.JButton();
        channel2jButton = new javax.swing.JButton();
        channel3jButton = new javax.swing.JButton();
        channel4jButton = new javax.swing.JButton();
        channel5jButton = new javax.swing.JButton();
        channel6jButton = new javax.swing.JButton();
        channel8jButton = new javax.swing.JButton();
        channel9jButton = new javax.swing.JButton();
        channel7jButton = new javax.swing.JButton();
        channel11jButton = new javax.swing.JButton();
        channel12jButton = new javax.swing.JButton();
        channel10jButton = new javax.swing.JButton();

        channel1jButton2.setText("87.5");

        channel2jButton2.setText("89.0");

        channel3jButton4.setText("92.0");

        channel3jButton5.setText("92.0");

        channel1jButton3.setText("87.5");

        channel2jButton3.setText("89.0");

        channel3jButton6.setText("92.0");

        channel3jButton7.setText("92.0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kanal Hafıza Listesi");
        setLocation(new java.awt.Point(530, 70));
        setMinimumSize(new java.awt.Dimension(275, 195));
        setPreferredSize(new java.awt.Dimension(275, 195));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        channel1jButton.setText("87.5");
        channel1jButton.setToolTipText("Kanal 1");
        channel1jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel1jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel1jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel1jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        channel2jButton.setText("90.0");
        channel2jButton.setToolTipText("Kanal 2");
        channel2jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel2jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel2jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel2jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        channel3jButton.setText("92.0");
        channel3jButton.setToolTipText("Kanal 3");
        channel3jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel3jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel3jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel3jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        channel4jButton.setText("94.0");
        channel4jButton.setToolTipText("Kanal 4");
        channel4jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel4jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel4jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel4jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        channel5jButton.setText("96.0");
        channel5jButton.setToolTipText("Kanal 5");
        channel5jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel5jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel5jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel5jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        channel6jButton.setText("98.0");
        channel6jButton.setToolTipText("Kanal 6");
        channel6jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel6jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel6jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel6jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        channel8jButton.setText("102.4");
        channel8jButton.setToolTipText("Kanal 8");
        channel8jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel8jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel8jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel8jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        channel9jButton.setText("104.0");
        channel9jButton.setToolTipText("Kanal 9");
        channel9jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel9jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel9jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel9jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        channel7jButton.setText("100.0");
        channel7jButton.setToolTipText("Kanal 7");
        channel7jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel7jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel7jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel7jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        channel11jButton.setText("107.2");
        channel11jButton.setToolTipText("Kanal 11");
        channel11jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel11jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel11jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel11jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        channel12jButton.setText("108.0");
        channel12jButton.setToolTipText("Kanal 12");
        channel12jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel12jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel12jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel12jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        channel10jButton.setText("106.0");
        channel10jButton.setToolTipText("Kanal 10");
        channel10jButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        channel10jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel10jButtonMouseClicked(evt);
            }
        });
        getContentPane().add(channel10jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void channel1jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel1jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel1jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel1jButton.getText());
        }
    }//GEN-LAST:event_channel1jButtonMouseClicked

    private void channel2jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel2jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel2jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel2jButton.getText());
        }
    }//GEN-LAST:event_channel2jButtonMouseClicked

    private void channel3jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel3jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel3jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel3jButton.getText());
        }
    }//GEN-LAST:event_channel3jButtonMouseClicked

    private void channel4jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel4jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel4jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel4jButton.getText());
        }
    }//GEN-LAST:event_channel4jButtonMouseClicked

    private void channel5jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel5jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel5jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel5jButton.getText());
        }
    }//GEN-LAST:event_channel5jButtonMouseClicked

    private void channel6jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel6jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel6jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel6jButton.getText());
        }
    }//GEN-LAST:event_channel6jButtonMouseClicked

    private void channel7jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel7jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel7jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel7jButton.getText());
        }
    }//GEN-LAST:event_channel7jButtonMouseClicked

    private void channel8jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel8jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel8jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel8jButton.getText());
        }
    }//GEN-LAST:event_channel8jButtonMouseClicked

    private void channel9jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel9jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel9jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel9jButton.getText());
        }
    }//GEN-LAST:event_channel9jButtonMouseClicked

    private void channel10jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel10jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel10jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel10jButton.getText());
        }
    }//GEN-LAST:event_channel10jButtonMouseClicked

    private void channel11jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel11jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel11jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel11jButton.getText());
        }
    }//GEN-LAST:event_channel11jButtonMouseClicked

    private void channel12jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel12jButtonMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            RadioMemorySaveJFrame radioMemorySaveJFrame = new RadioMemorySaveJFrame(this.radioFrame, true);
            radioMemorySaveJFrame.setAlwaysOnTop(true);
            radioMemorySaveJFrame.setVisible(true);
            radioMemorySaveJFrame.toFront();
            radioMemorySaveJFrame.transferFocus();
            if (radioMemorySaveJFrame.getReturnStatus() == 1) {
                this.channel12jButton.setText(this.radioFrame.getFrequance1() + "." + this.radioFrame.getFrequance2());
                saveAllFrequance();
            }
        } else {
            this.setFrequance(this.channel12jButton.getText());
        }
    }//GEN-LAST:event_channel12jButtonMouseClicked

    private void setFrequance(String freqText) {
        this.radioFrame.setFrequance(Integer.parseInt(freqText.replace(".", "")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton channel10jButton;
    private javax.swing.JButton channel11jButton;
    private javax.swing.JButton channel12jButton;
    private javax.swing.JButton channel1jButton;
    private javax.swing.JButton channel1jButton2;
    private javax.swing.JButton channel1jButton3;
    private javax.swing.JButton channel2jButton;
    private javax.swing.JButton channel2jButton2;
    private javax.swing.JButton channel2jButton3;
    private javax.swing.JButton channel3jButton;
    private javax.swing.JButton channel3jButton4;
    private javax.swing.JButton channel3jButton5;
    private javax.swing.JButton channel3jButton6;
    private javax.swing.JButton channel3jButton7;
    private javax.swing.JButton channel4jButton;
    private javax.swing.JButton channel5jButton;
    private javax.swing.JButton channel6jButton;
    private javax.swing.JButton channel7jButton;
    private javax.swing.JButton channel8jButton;
    private javax.swing.JButton channel9jButton;
    // End of variables declaration//GEN-END:variables

    private void loadAllFrequance() {
        ArrayList<String> freqList = RadioMemoryJFrame.readFrequanceListFromFile();
        if ((freqList == null) || (freqList.size() != 12)) {
            return;
        }
        this.channel1jButton.setText(freqList.get(0));
        this.channel2jButton.setText(freqList.get(1));
        this.channel3jButton.setText(freqList.get(2));
        this.channel4jButton.setText(freqList.get(3));
        this.channel5jButton.setText(freqList.get(4));
        this.channel6jButton.setText(freqList.get(5));
        this.channel7jButton.setText(freqList.get(6));
        this.channel8jButton.setText(freqList.get(7));
        this.channel9jButton.setText(freqList.get(8));
        this.channel10jButton.setText(freqList.get(9));
        this.channel11jButton.setText(freqList.get(10));
        this.channel12jButton.setText(freqList.get(11));
    }
    
    private void saveAllFrequance() {
        ArrayList lines = new ArrayList<String>();
        lines.add(this.channel1jButton.getText());
        lines.add(this.channel2jButton.getText());
        lines.add(this.channel3jButton.getText());
        lines.add(this.channel4jButton.getText());
        lines.add(this.channel5jButton.getText());
        lines.add(this.channel6jButton.getText());
        lines.add(this.channel7jButton.getText());
        lines.add(this.channel8jButton.getText());
        lines.add(this.channel9jButton.getText());
        lines.add(this.channel10jButton.getText());
        lines.add(this.channel11jButton.getText());
        lines.add(this.channel12jButton.getText());
        
        RadioMemoryJFrame.writeFrequanceListToFile(lines);
    }
    
    private static void writeFrequanceListToFile(ArrayList<String> list) {
        try (Writer writer = new FileWriter(ConfigClass.CHANNEL_FILE)) {
            new Gson().toJson(list, writer);
            writer.close();
        } catch (IOException e) {
            try {
                File file = new File(ConfigClass.CHANNEL_FILE);
                file.createNewFile(); // Dosya yoksa oluştur
                FileWriter writer = new FileWriter(file);
                Gson gson = new Gson();
                gson.toJson(list, writer);
                writer.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    private static ArrayList<String> readFrequanceListFromFile() {
        var lines = new ArrayList<String>();
        try (Reader reader = new FileReader(ConfigClass.CHANNEL_FILE)) {
            lines = new Gson().fromJson(reader, new TypeToken<ArrayList<String>>() {}.getType());
        } catch (IOException e) {
             e.printStackTrace();
            return null;
        }
        return lines;
    }
    
}
